version: '2.3'

services: 
    app:
        build: devops/php/
        volumes: 
            - .:/var/www
        networks: 
            - fullcycle-laravel-network
        depends_on:
            db:
                condition: service_healthy
    nginx:
        build: devops/nginx/
        restart: unless-stopped
        volumes: 
            - .:/var/www
        ports: 
            - "8000:80"
        networks: 
            - fullcycle-laravel-network
        depends_on:
            - app
    
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        restart: always
        environment: 
            - "MYSQL_ROOT_PASSWORD=laravel"
            - "MYSQL_DATABASE=laravel"
            - "MYSQL_USER=root"
        networks:
            - fullcycle-laravel-network
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql/
        healthcheck:
            test: ["CMD-SHELL", 'mysql -uroot --password=laravel --database=laravel --execute="SELECT 1"']
            timeout: 10s
            interval: 10s
            retries: 4
    
    redis:
        image: redis:alpine
        expose: 
            - 6379
        networks:
            - fullcycle-laravel-network

volumes:
    db-data:
networks: 
    fullcycle-laravel-network:
        driver: bridge